SELECT
    ce.ano,
    m.municipio,
    ce.cod_escola,
    ce.situacao_funcionamento,
    ce.tp_dependencia,
    ce.tp_localizacao,
    LOWER(TRIM(ce.dependencia)) AS dependencia,
    ce.mat_basico,
    ce.mat_basico_integral,
    ce.mat_basico_0_3,
    ce.docentes_basico,
    ce.escolas_com_internet,
    ce.in_agua_potavel,
    ce.in_energia_inexistente,
    ce.escolas_com_internet AS in_internet,
    ce.in_biblioteca_sala_leitura,
    ce.in_quadra_esportes,
    ce.in_esgoto_rede_publica,
    ce.escolas_com_internet_alunos,
    ce.escolas_com_internet_aprendizagem,
    ce.escolas_com_internet_comunidade,
    ce.escolas_com_acesso_internet_computador,
    ce.escolas_com_acesso_internet_disp_pessoais,
    ce.escolas_com_banda_larga,
    ce.escolas_com_rede_local,
    ce.escolas_com_rede_local_wireless,
    ce.escolas_com_rede_local_cabo_wireless,
    ce.escolas_com_educacao_ambiental,
    ce.escolas_com_orgao_conselho_escolar,
    ce.tp_proposta_pedagogica,
    ce.escolas_com_desktop_aluno,
    ce.escolas_com_comp_portatil_aluno,
    ce.escolas_com_tablet_aluno,
    ce.qt_salas_utilizadas,
    ce.qt_salas_utiliza_climatizadas,
    ce.qt_salas_utilizadas_acessiveis
FROM censo_escolas ce
JOIN municipios m
    ON ce.id_municipio::text = m.id_municipio::text;
