export type MunicipalReportCoverage = 'complete' | 'partial' | 'future_integration'

export interface MunicipalReportCoverageEntry {
  section: number
  components: string[]
  dataFiles: string[]
  sources: string[]
  years: string[]
  charts: string[]
  tables: string[]
  narratives: string[]
  coverage: MunicipalReportCoverage
}

// Inventário interno de arquitetura. Não deve ser renderizado na página pública.
export const MUNICIPAL_REPORT_COVERAGE_INVENTORY: MunicipalReportCoverageEntry[] = [
  { section: 1, components: ['MunicipalTechnicalReport'], dataFiles: ['municipal overview'], sources: ['Identificação municipal'], years: ['referência vigente'], charts: [], tables: [], narratives: ['identificação'], coverage: 'partial' },
  { section: 2, components: ['SnapshotSummary', 'StageOfferTable', 'IndicatorTable'], dataFiles: ['municipal overview', 'education municipality document', 'diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar', 'base populacional do diagnóstico', 'INEP — Média de Alunos por Turma (ATU)'], years: ['2025', 'último ano por indicador'], charts: [], tables: ['matrículas por rede', 'atendimento estimado de 0 a 5 anos', 'média de alunos por turma'], narratives: ['nota sobre bases territoriais distintas'], coverage: 'partial' },
  { section: 3, components: ['SnapshotSummary', 'StageOfferTable', 'IndicatorTable'], dataFiles: ['municipal overview', 'education municipality document', 'diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar', 'base populacional do diagnóstico', 'INEP — Média de Alunos por Turma (ATU)'], years: ['2025', 'último ano por indicador'], charts: [], tables: ['matrículas por rede', 'atendimento estimado de 6 a 17 anos', 'média de alunos por turma'], narratives: ['nota sobre bases territoriais distintas'], coverage: 'partial' },
  { section: 4, components: ['SnapshotSummary', 'StageOfferTable', 'IndicatorTable'], dataFiles: ['municipal overview', 'education municipality document', 'diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar', 'INEP — Taxas de Rendimento Escolar', 'base populacional do diagnóstico', 'INEP — Média de Alunos por Turma (ATU)'], years: ['2025', 'último ano por indicador'], charts: [], tables: ['matrículas por rede', 'rendimento escolar', 'atendimento estimado de 15 a 17 anos', 'média de alunos por turma'], narratives: ['nota sobre o indicador contextual de atendimento'], coverage: 'partial' },
  { section: 5, components: ['IndicatorTable'], dataFiles: ['education municipality document', 'diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar'], years: ['último ano por indicador'], charts: [], tables: ['oferta geral em tempo integral', 'alunos e escolas da rede pública com jornada integral'], narratives: ['distinção entre os universos dos indicadores'], coverage: 'partial' },
  { section: 6, components: ['IndicatorTable'], dataFiles: ['diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar'], years: ['a partir de 2024'], charts: [], tables: ['escolas que promovem educação ambiental'], narratives: ['caráter declaratório do indicador'], coverage: 'partial' },
  { section: 7, components: ['IndicatorTable'], dataFiles: ['education municipality document'], sources: ['INEP', 'IBGE'], years: ['último ano publicado'], charts: [], tables: ['recortes indígenas e rurais'], narratives: ['limites territoriais'], coverage: 'partial' },
  { section: 8, components: ['SnapshotSummary', 'IndicatorTable'], dataFiles: ['municipal overview', 'education municipality document', 'diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar', 'INEP — Sinopse Estatística da Educação Básica'], years: ['2025', 'último ano por indicador'], charts: [], tables: ['matrículas da EJA', 'EJA articulada à Educação Profissional'], narratives: ['universo do numerador e do denominador da articulação profissional'], coverage: 'partial' },
  { section: 9, components: ['SnapshotSummary', 'SpecialEducationTechnicalReportSummary'], dataFiles: ['municipal overview', 'special-education-v1'], sources: ['INEP — Censo Escolar'], years: ['2014–2025', 'Educação Bilíngue de Surdos em 2025'], charts: [], tables: ['inclusão em classes comuns, AEE, sala de recursos e Educação Bilíngue de Surdos'], narratives: ['recorte transversal e limites da oferta de AEE'], coverage: 'partial' },
  { section: 10, components: ['HigherEducationReportContent'], dataFiles: ['higher education municipality document'], sources: ['INEP — Sinopse Estatística da Educação Superior'], years: ['último ano municipal utilizável'], charts: [], tables: ['indicadores de graduação'], narratives: ['limite sobre pós-graduação'], coverage: 'partial' },
  { section: 11, components: ['SnapshotSummary', 'IndicatorTable'], dataFiles: ['municipal overview', 'education municipality document'], sources: ['INEP'], years: ['2025', 'último ano publicado'], charts: [], tables: ['ofertas profissionais'], narratives: [], coverage: 'partial' },
  { section: 12, components: ['IndicatorTable'], dataFiles: ['education municipality document', 'diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar', 'INEP — Média de Alunos por Turma (ATU)'], years: ['último ano por indicador'], charts: [], tables: ['docentes por etapa', 'média de alunos por turma', 'adequação da formação docente', 'pós-graduação e vínculos temporários'], narratives: ['limites de recomposição dos percentuais publicados'], coverage: 'partial' },
  { section: 13, components: ['IndicatorTable'], dataFiles: ['diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar'], years: ['último ano por indicador'], charts: [], tables: ['conselho escolar e proposta pedagógica'], narratives: ['caráter declaratório dos indicadores'], coverage: 'partial' },
  { section: 14, components: ['SchoolInfrastructureReportTable', 'IndicatorTable'], dataFiles: ['school infrastructure contract', 'education municipality document', 'diagnóstico público PNE 2026–2036'], sources: ['INEP — Censo Escolar'], years: ['2025', 'último ano por indicador'], charts: [], tables: ['infraestrutura por total e rede municipal', 'conectividade e equipamentos', 'salas climatizadas e acessíveis'], narratives: ['metodologia do contrato canônico', 'distinção entre percentuais de escolas e de salas utilizadas'], coverage: 'partial' },
  { section: 15, components: ['links para módulos financeiros'], dataFiles: ['módulos financeiros'], sources: ['fontes próprias dos módulos'], years: ['conforme o módulo'], charts: [], tables: [], narratives: ['referência aos contratos homologados'], coverage: 'partial' },
  { section: 16, components: ['link para cenários de atendimento'], dataFiles: ['projeções e cenários'], sources: ['INEP', 'IBGE'], years: ['histórico e horizonte vigente'], charts: [], tables: [], narratives: ['distinção entre observado e projetado'], coverage: 'partial' },
  { section: 17, components: ['PmeReferenceIndicatorsTable'], dataFiles: ['diagnóstico público PNE 2026–2036'], sources: ['fontes declaradas pelo diagnóstico'], years: ['último ano por indicador'], charts: [], tables: ['situação atual em relação à referência'], narratives: ['nota de interpretação'], coverage: 'partial' },
  { section: 18, components: ['MunicipalTechnicalReport'], dataFiles: ['metadados do municipal overview'], sources: ['fontes declaradas'], years: ['referência vigente'], charts: [], tables: [], narratives: ['metodologia e limitações'], coverage: 'complete' },
  { section: 19, components: ['ReportTableRegion', 'PmeReferenceIndicatorsTable'], dataFiles: ['contratos consumidos pelo relatório', 'diagnóstico público PNE 2026–2036', 'metadados de fontes'], sources: ['INEP', 'IBGE', 'fontes declaradas pelo diagnóstico'], years: ['por base e indicador'], charts: [], tables: ['rastreabilidade pública', 'série histórica', 'referências do PNE'], narratives: ['notas metodológicas e limitações'], coverage: 'partial' },
]
